// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (process.report && typeof process.report.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./longbridge.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('longbridge-android-arm64')
        const bindingPackageVersion = require('longbridge-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./longbridge.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('longbridge-android-arm-eabi')
        const bindingPackageVersion = require('longbridge-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if ((process.config && process.config.variables && process.config.variables.shlib_suffix === 'dll.a') || (process.config && process.config.variables && process.config.variables.node_target_type === 'shared_library')) {
        try {
        return require('./longbridge.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('longbridge-win32-x64-gnu')
        const bindingPackageVersion = require('longbridge-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./longbridge.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('longbridge-win32-x64-msvc')
        const bindingPackageVersion = require('longbridge-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./longbridge.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('longbridge-win32-ia32-msvc')
        const bindingPackageVersion = require('longbridge-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./longbridge.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('longbridge-win32-arm64-msvc')
        const bindingPackageVersion = require('longbridge-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./longbridge.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('longbridge-darwin-universal')
      const bindingPackageVersion = require('longbridge-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./longbridge.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('longbridge-darwin-x64')
        const bindingPackageVersion = require('longbridge-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./longbridge.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('longbridge-darwin-arm64')
        const bindingPackageVersion = require('longbridge-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./longbridge.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('longbridge-freebsd-x64')
        const bindingPackageVersion = require('longbridge-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./longbridge.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('longbridge-freebsd-arm64')
        const bindingPackageVersion = require('longbridge-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./longbridge.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('longbridge-linux-x64-musl')
          const bindingPackageVersion = require('longbridge-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./longbridge.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('longbridge-linux-x64-gnu')
          const bindingPackageVersion = require('longbridge-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./longbridge.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('longbridge-linux-arm64-musl')
          const bindingPackageVersion = require('longbridge-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./longbridge.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('longbridge-linux-arm64-gnu')
          const bindingPackageVersion = require('longbridge-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./longbridge.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('longbridge-linux-arm-musleabihf')
          const bindingPackageVersion = require('longbridge-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./longbridge.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('longbridge-linux-arm-gnueabihf')
          const bindingPackageVersion = require('longbridge-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./longbridge.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('longbridge-linux-loong64-musl')
          const bindingPackageVersion = require('longbridge-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./longbridge.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('longbridge-linux-loong64-gnu')
          const bindingPackageVersion = require('longbridge-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./longbridge.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('longbridge-linux-riscv64-musl')
          const bindingPackageVersion = require('longbridge-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./longbridge.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('longbridge-linux-riscv64-gnu')
          const bindingPackageVersion = require('longbridge-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./longbridge.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('longbridge-linux-ppc64-gnu')
        const bindingPackageVersion = require('longbridge-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./longbridge.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('longbridge-linux-s390x-gnu')
        const bindingPackageVersion = require('longbridge-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./longbridge.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('longbridge-openharmony-arm64')
        const bindingPackageVersion = require('longbridge-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./longbridge.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('longbridge-openharmony-x64')
        const bindingPackageVersion = require('longbridge-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./longbridge.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('longbridge-openharmony-arm')
        const bindingPackageVersion = require('longbridge-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

function createLoadErrorChain(errors) {
  return errors.reduce((previous, current) => {
    let message
    try {
      message =
        current && typeof current.message === 'string'
          ? current.message
          : String(current)
    } catch {
      message = 'Unknown error'
    }
    const error = new Error(message)
    error.cause = previous
    return error
  }, null)
}

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value → native binding preferred, WASI is only a fallback
//   'true'                   → prefer WASI, but retain native as a lazy fallback
//   'error'                  → require WASI without initializing a native fallback
// Treating any non-empty string as truthy (the historical behavior) meant
// NAPI_RS_FORCE_WASI=false, NAPI_RS_FORCE_WASI=0, etc. inadvertently triggered
// the WASI path, causing ENOENT for packages shipped without a .wasi.cjs file.
//
// NAPI_RS_WASI_FLAVOR selects one exact generated flavor and implies strict
// WASI loading. It never crosses into another flavor or falls back to native.
const __napiWasiFlavors = ["wasm32-wasi"]
const __napiWasiFlavor = process.env.NAPI_RS_WASI_FLAVOR
const __napiWasiFlavorRequested =
  typeof __napiWasiFlavor === 'string' && __napiWasiFlavor.length > 0
if (
  __napiWasiFlavorRequested &&
  __napiWasiFlavors.indexOf(__napiWasiFlavor) === -1
) {
  throw new Error(
    'Unsupported WASI flavor "' +
      __napiWasiFlavor +
      '". Available flavors: ' +
      __napiWasiFlavors.join(', '),
  )
}
const forceWasiError = process.env.NAPI_RS_FORCE_WASI === 'error'
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === 'true' ||
  forceWasiError ||
  __napiWasiFlavorRequested

if (!forceWasi) {
  nativeBinding = requireNative()
}

if (!nativeBinding || forceWasi) {
  let wasiBinding = null
  let wasiBindingLoaded = false
  const wasiBindingErrors = []
  const __napiWasiResolveCandidate = (specifier, isPackage, localArtifacts) => {
    try {
      require.resolve(specifier)
    } catch (resolveError) {
      if (!resolveError || resolveError.code !== 'MODULE_NOT_FOUND') {
        throw resolveError
      }
      if (isPackage) {
        try {
          require.resolve(specifier + '/package.json')
        } catch (packageError) {
          if (packageError && packageError.code === 'MODULE_NOT_FOUND') {
            return resolveError
          }
          // An exports restriction proves the package exists even when its
          // package.json is not public. Preserve the root resolution failure.
          throw resolveError
        }
        // The package exists but its main/export target is broken.
        throw resolveError
      }
      return resolveError
    }
    if (localArtifacts) {
      let artifactError = null
      for (let i = 0; i < localArtifacts.length; i++) {
        try {
          require.resolve(localArtifacts[i])
          return null
        } catch (resolveError) {
          if (!resolveError || resolveError.code !== 'MODULE_NOT_FOUND') {
            throw resolveError
          }
          artifactError = resolveError
        }
      }
      return artifactError
    }
    return null
  }
  if (!wasiBindingLoaded && (!__napiWasiFlavorRequested || __napiWasiFlavor === "wasm32-wasi")) {
    let candidateError = null
    let candidateFailed = false
    try {
      candidateError = __napiWasiResolveCandidate('./longbridge.wasi.cjs', false, ["./longbridge.wasm32-wasi.debug.wasm","./longbridge.wasm32-wasi.wasm"])
      candidateFailed = candidateError !== null
      if (!candidateFailed) {
        wasiBinding = require('./longbridge.wasi.cjs')
        nativeBinding = wasiBinding
        wasiBindingLoaded = true
      }
    } catch (err) {
      candidateError = err
      candidateFailed = true
    }
    if (candidateFailed) {
      wasiBindingErrors.push(candidateError)
      loadErrors.push(candidateError)
    }
  }
  if (!wasiBindingLoaded && (!__napiWasiFlavorRequested || __napiWasiFlavor === "wasm32-wasi")) {
    let candidateError = null
    let candidateFailed = false
    try {
      candidateError = __napiWasiResolveCandidate('longbridge-wasm32-wasi', true, undefined)
      candidateFailed = candidateError !== null
      if (!candidateFailed) {
        if (process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          const bindingPackageVersion = require('longbridge-wasm32-wasi/package.json').version
          if (bindingPackageVersion !== '0.0.0') {
            throw new Error(`WASI binding package version mismatch, expected 0.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
        }
        wasiBinding = require('longbridge-wasm32-wasi')
        nativeBinding = wasiBinding
        wasiBindingLoaded = true
      }
    } catch (err) {
      candidateError = err
      candidateFailed = true
    }
    if (candidateFailed) {
      wasiBindingErrors.push(candidateError)
      loadErrors.push(candidateError)
    }
  }
  if (
    !wasiBindingLoaded &&
    forceWasi &&
    !forceWasiError &&
    !__napiWasiFlavorRequested
  ) {
    nativeBinding = requireNative()
  }
  if ((forceWasiError || __napiWasiFlavorRequested) && !wasiBindingLoaded) {
    const error = new Error(
      __napiWasiFlavorRequested
        ? 'WASI binding for flavor "' + __napiWasiFlavor + '" not found'
        : 'WASI binding not found and NAPI_RS_FORCE_WASI is set to error',
    )
    error.cause = createLoadErrorChain(wasiBindingErrors)
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const error = new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
    )
    // assign instead of the `new Error(message, { cause })` options form,
    // which Node < 16.9 silently ignores
    error.cause = createLoadErrorChain(loadErrors)
    throw error
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.AccountBalance = nativeBinding.AccountBalance
module.exports.AgentContext = nativeBinding.AgentContext
module.exports.AlertContext = nativeBinding.AlertContext
module.exports.AllExecutionsResponse = nativeBinding.AllExecutionsResponse
module.exports.AssetContext = nativeBinding.AssetContext
module.exports.AttachedOrderDetail = nativeBinding.AttachedOrderDetail
module.exports.Brokers = nativeBinding.Brokers
module.exports.CalendarContext = nativeBinding.CalendarContext
module.exports.Candlestick = nativeBinding.Candlestick
module.exports.CapitalDistribution = nativeBinding.CapitalDistribution
module.exports.CapitalDistributionResponse = nativeBinding.CapitalDistributionResponse
module.exports.CapitalFlowLine = nativeBinding.CapitalFlowLine
module.exports.CashFlow = nativeBinding.CashFlow
module.exports.CashInfo = nativeBinding.CashInfo
module.exports.Config = nativeBinding.Config
module.exports.ContentContext = nativeBinding.ContentContext
module.exports.DcaContext = nativeBinding.DcaContext
module.exports.DCAContext = nativeBinding.DCAContext
module.exports.Decimal = nativeBinding.Decimal
module.exports.Depth = nativeBinding.Depth
module.exports.EstimateMaxPurchaseQuantityResponse = nativeBinding.EstimateMaxPurchaseQuantityResponse
module.exports.Execution = nativeBinding.Execution
module.exports.FilingItem = nativeBinding.FilingItem
module.exports.FrozenTransactionFee = nativeBinding.FrozenTransactionFee
module.exports.FundamentalContext = nativeBinding.FundamentalContext
module.exports.FundPosition = nativeBinding.FundPosition
module.exports.FundPositionChannel = nativeBinding.FundPositionChannel
module.exports.FundPositionsResponse = nativeBinding.FundPositionsResponse
module.exports.GridBidSize = nativeBinding.GridBidSize
module.exports.GridChannelInfo = nativeBinding.GridChannelInfo
module.exports.GridContext = nativeBinding.GridContext
module.exports.GridOrder = nativeBinding.GridOrder
module.exports.GridOrderDetail = nativeBinding.GridOrderDetail
module.exports.GridOrderHistory = nativeBinding.GridOrderHistory
module.exports.GridOrdersResponse = nativeBinding.GridOrdersResponse
module.exports.GridOrderSubOrder = nativeBinding.GridOrderSubOrder
module.exports.GridSymbolInfo = nativeBinding.GridSymbolInfo
module.exports.GridTriggerHistoryResponse = nativeBinding.GridTriggerHistoryResponse
module.exports.HistoryMarketTemperatureResponse = nativeBinding.HistoryMarketTemperatureResponse
module.exports.HttpClient = nativeBinding.HttpClient
module.exports.IntradayLine = nativeBinding.IntradayLine
module.exports.IssuerInfo = nativeBinding.IssuerInfo
module.exports.MarginRatio = nativeBinding.MarginRatio
module.exports.MarketContext = nativeBinding.MarketContext
module.exports.MarketTemperature = nativeBinding.MarketTemperature
module.exports.MarketTradingDays = nativeBinding.MarketTradingDays
module.exports.MarketTradingSession = nativeBinding.MarketTradingSession
module.exports.NaiveDate = nativeBinding.NaiveDate
module.exports.NaiveDatetime = nativeBinding.NaiveDatetime
module.exports.NewsItem = nativeBinding.NewsItem
module.exports.OAuth = nativeBinding.OAuth
module.exports.OptionQuote = nativeBinding.OptionQuote
module.exports.OptionVolumeDaily = nativeBinding.OptionVolumeDaily
module.exports.OptionVolumeDailyStat = nativeBinding.OptionVolumeDailyStat
module.exports.Order = nativeBinding.Order
module.exports.OrderChargeDetail = nativeBinding.OrderChargeDetail
module.exports.OrderChargeFee = nativeBinding.OrderChargeFee
module.exports.OrderChargeItem = nativeBinding.OrderChargeItem
module.exports.OrderDetail = nativeBinding.OrderDetail
module.exports.OrderHistoryDetail = nativeBinding.OrderHistoryDetail
module.exports.OwnedTopic = nativeBinding.OwnedTopic
module.exports.ParticipantInfo = nativeBinding.ParticipantInfo
module.exports.PortfolioContext = nativeBinding.PortfolioContext
module.exports.PrePostQuote = nativeBinding.PrePostQuote
module.exports.PushBrokers = nativeBinding.PushBrokers
module.exports.PushBrokersEvent = nativeBinding.PushBrokersEvent
module.exports.PushCandlestick = nativeBinding.PushCandlestick
module.exports.PushCandlestickEvent = nativeBinding.PushCandlestickEvent
module.exports.PushDepth = nativeBinding.PushDepth
module.exports.PushDepthEvent = nativeBinding.PushDepthEvent
module.exports.PushGridOrderChanged = nativeBinding.PushGridOrderChanged
module.exports.PushOrderChanged = nativeBinding.PushOrderChanged
module.exports.PushQuote = nativeBinding.PushQuote
module.exports.PushQuoteEvent = nativeBinding.PushQuoteEvent
module.exports.PushTrades = nativeBinding.PushTrades
module.exports.PushTradesEvent = nativeBinding.PushTradesEvent
module.exports.QuoteContext = nativeBinding.QuoteContext
module.exports.QuotePackageDetail = nativeBinding.QuotePackageDetail
module.exports.RealtimeQuote = nativeBinding.RealtimeQuote
module.exports.ScreenerContext = nativeBinding.ScreenerContext
module.exports.Security = nativeBinding.Security
module.exports.SecurityBrokers = nativeBinding.SecurityBrokers
module.exports.SecurityCalcIndex = nativeBinding.SecurityCalcIndex
module.exports.SecurityDepth = nativeBinding.SecurityDepth
module.exports.SecurityQuote = nativeBinding.SecurityQuote
module.exports.SecurityStaticInfo = nativeBinding.SecurityStaticInfo
module.exports.SharelistContext = nativeBinding.SharelistContext
module.exports.StockPosition = nativeBinding.StockPosition
module.exports.StockPositionChannel = nativeBinding.StockPositionChannel
module.exports.StockPositionsResponse = nativeBinding.StockPositionsResponse
module.exports.StrikePriceInfo = nativeBinding.StrikePriceInfo
module.exports.SubmitGridOrderResponse = nativeBinding.SubmitGridOrderResponse
module.exports.SubmitOrderResponse = nativeBinding.SubmitOrderResponse
module.exports.Subscription = nativeBinding.Subscription
module.exports.Time = nativeBinding.Time
module.exports.TopicAuthor = nativeBinding.TopicAuthor
module.exports.TopicImage = nativeBinding.TopicImage
module.exports.TopicItem = nativeBinding.TopicItem
module.exports.Trade = nativeBinding.Trade
module.exports.TradeContext = nativeBinding.TradeContext
module.exports.TradingSessionInfo = nativeBinding.TradingSessionInfo
module.exports.TriggerOrder = nativeBinding.TriggerOrder
module.exports.WarrantInfo = nativeBinding.WarrantInfo
module.exports.WarrantQuote = nativeBinding.WarrantQuote
module.exports.WatchlistGroup = nativeBinding.WatchlistGroup
module.exports.WatchlistSecurity = nativeBinding.WatchlistSecurity
module.exports.AdjustType = nativeBinding.AdjustType
module.exports.AhPremiumPeriod = nativeBinding.AhPremiumPeriod
module.exports.AlertCondition = nativeBinding.AlertCondition
module.exports.AlertFrequency = nativeBinding.AlertFrequency
module.exports.AssetType = nativeBinding.AssetType
module.exports.AttachedOrderType = nativeBinding.AttachedOrderType
module.exports.BalanceType = nativeBinding.BalanceType
module.exports.BrokerHoldingPeriod = nativeBinding.BrokerHoldingPeriod
module.exports.CalcIndex = nativeBinding.CalcIndex
module.exports.CalendarCategory = nativeBinding.CalendarCategory
module.exports.CashFlowDirection = nativeBinding.CashFlowDirection
module.exports.ChargeCategoryCode = nativeBinding.ChargeCategoryCode
module.exports.CommissionFreeStatus = nativeBinding.CommissionFreeStatus
module.exports.ConversationStatus = nativeBinding.ConversationStatus
module.exports.DCAFrequency = nativeBinding.DCAFrequency
module.exports.DCAStatus = nativeBinding.DCAStatus
module.exports.DeductionStatus = nativeBinding.DeductionStatus
module.exports.DerivativeType = nativeBinding.DerivativeType
module.exports.ElementType = nativeBinding.ElementType
module.exports.FilterWarrantExpiryDate = nativeBinding.FilterWarrantExpiryDate
module.exports.FilterWarrantInOutBoundsType = nativeBinding.FilterWarrantInOutBoundsType
module.exports.FinancialReportKind = nativeBinding.FinancialReportKind
module.exports.FinancialReportPeriod = nativeBinding.FinancialReportPeriod
module.exports.FlowDirection = nativeBinding.FlowDirection
module.exports.Granularity = nativeBinding.Granularity
module.exports.GridLimitEvent = nativeBinding.GridLimitEvent
module.exports.GridTimeInForce = nativeBinding.GridTimeInForce
module.exports.InstitutionRecommend = nativeBinding.InstitutionRecommend
module.exports.Language = nativeBinding.Language
module.exports.MacroeconomicCountry = nativeBinding.MacroeconomicCountry
module.exports.Market = nativeBinding.Market
module.exports.OptionDirection = nativeBinding.OptionDirection
module.exports.OptionType = nativeBinding.OptionType
module.exports.OrderSide = nativeBinding.OrderSide
module.exports.OrderStatus = nativeBinding.OrderStatus
module.exports.OrderTag = nativeBinding.OrderTag
module.exports.OrderType = nativeBinding.OrderType
module.exports.OutsideRTH = nativeBinding.OutsideRTH
module.exports.Period = nativeBinding.Period
module.exports.PinnedMode = nativeBinding.PinnedMode
module.exports.PushCandlestickMode = nativeBinding.PushCandlestickMode
module.exports.SecuritiesUpdateMode = nativeBinding.SecuritiesUpdateMode
module.exports.SecurityBoard = nativeBinding.SecurityBoard
module.exports.SecurityListCategory = nativeBinding.SecurityListCategory
module.exports.SortOrderType = nativeBinding.SortOrderType
module.exports.StatementType = nativeBinding.StatementType
module.exports.SubType = nativeBinding.SubType
module.exports.TimeInForceType = nativeBinding.TimeInForceType
module.exports.TopicType = nativeBinding.TopicType
module.exports.TradeDirection = nativeBinding.TradeDirection
module.exports.TradeSession = nativeBinding.TradeSession
module.exports.TradeSessions = nativeBinding.TradeSessions
module.exports.TradeStatus = nativeBinding.TradeStatus
module.exports.TriggerPriceType = nativeBinding.TriggerPriceType
module.exports.TriggerStatus = nativeBinding.TriggerStatus
module.exports.WarrantSortBy = nativeBinding.WarrantSortBy
module.exports.WarrantStatus = nativeBinding.WarrantStatus
module.exports.WarrantType = nativeBinding.WarrantType
